### ISSUE TITLE
请问这里怎么调用到server的函数的？

### ISSUE THREAD

**Issue by charles4cc** [heucoder/thrift_practice#1]
https://github.com/heucoder/thrift_practice/blob/1b51da3828d89b431fea05d626d5654e40fd7526/idl/gen-py/com/test/posResp.py#L49

**Comment by heucoder** [comment]
加qq说吧 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;charles4cc&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月7日(星期一) 下午4:50
收件人:&nbsp;&quot;heucoder/thrift_practice&quot;<thrift_practice@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[heucoder/thrift_practice] 请问这里怎么调用到server的函数的？ (#1)

**Comment by charles4cc** [comment]
好的。511757868。多谢了。请问你的昵称是什么？

**Comment by heucoder** [comment]
qq邮箱。我用的就是qq号------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;charles4cc&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:15
收件人:&nbsp;&quot;heucoder/thrift_practice&quot;<thrift_practice@noreply.github.com&gt;;
抄送:&nbsp;&quot;Heucoder&quot;<812860165@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [heucoder/thrift_practice] 请问这里怎么调用到server的函数的？ (#1)
